apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp3-deployment
  labels:
    app: flaskapp3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp3
  template:
    metadata:
      labels:
        app: flaskapp3
    spec:
      containers:
      - name: flaskapp3
        image: gabytal333/flaskapp3  
        ports:
        - containerPort: 5000