apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp1-deployment
  labels:
    app: flaskapp1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp1
  template:
    metadata:
      labels:
        app: flaskapp1
    spec:
      containers:
      - name: flaskapp1
        image: gabytal333/flaskapp1  
        ports:
        - containerPort: 5000