apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp2-deployment
  labels:
    app: flaskapp2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp2
  template:
    metadata:
      labels:
        app: flaskapp2
    spec:
      containers:
      - name: flaskapp2
        image: gabytal333/flaskapp2  
        ports:
        - containerPort: 5000